Repository ferntechsolutions/aiwcore, pull requests merged in 2020-04, with the labels that each got.

#3 redone all with the template
  frontend/package.json
  frontend/public/index.html
  frontend/src/App.js
  frontend/src/components/botListPage/BotListPage.js
  frontend/src/components/botListPage/BotLog.js
  frontend/src/components/botListPage/BotTable.js
  frontend/src/components/botListPage/RowInfo.js
  frontend/src/components/loginPage/Login.js
  frontend/src/components/navBar/NavBar.js
Labels: documentation, enhancement

#4 API && IPC render process
  backend/dataControl/botlist.json
  backend/server.js
  core/electron.js
  core/windows/content.js
  docs/GIT_HACK.md
  frontend/package.json
  frontend/src/App.js
  frontend/src/components/loginPage/Login.js
  frontend/src/electronScript.js
Labels: enhancement, help wanted

#23 Animated SearchBar added
  frontend/public/assets/css/style.css
  frontend/src/components/botEditPage/BotBuildPage.js
  frontend/src/components/botEditPage/SearchBar.js
Labels: documentation

#25 Update Api bug resolved
  .github/ISSUE_TEMPLATE/pull-request.md
  backend/dataControl/botlist.js
  backend/dataControl/botlist.json
  backend/server.js
Labels: good first issue

#26 IPC || server APi || log files
  backend/dataControl/botlist.js
  core/electron.js
  frontend/src/electronScript.js
  log.txt
  log_details.txt
Labels: enhancement, help wanted
